### ISSUE TITLE
Missing reference

### ISSUE THREAD

**Issue by randym32** [codaris/Anki.Vector.SDK#3]
When I try to build, I get errors for Anki.Vector.SDK\Anki.Vector\ExternalInterface\HttpRestMetaData.cs	 :
Error	CS0234	The type or namespace name 'DataAnnotations' does not exist in the namespace 'System.ComponentModel' (are you missing an assembly reference?)

**Comment by codaris** [comment]
It seems that namespace isn't defined in NetStandard even though it's in the framework and core.  

I'll have to think of how to resolve that as it provides a necessary feature.  I'm surprised I had no problems building it myself.

**Comment by codaris** [comment]
There is a separate package "System.ComponentModel.Annotations" that should fix the problem.  I will be adding that to the library after I give it some testing.  I would like to know if it fixes your build problems.

**Comment by codaris** [comment]
Seems to be no good solution so I just hard-coded the MetaDataAttribute class right into HttpRestMetaData.cs for now if you grab the latest code.  I suppose I might have to give up on providing the meta data that way and just serialize/deserialize the JSON objects manually.
